# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Heather Makes...
tagline:             'wonderful things'
description:         'Share my love of creating'
url:                 http://jeffarthur.co.uk/heathermakes
baseurl:             '/heathermakes'
paginate:            5

# About/contact
author:
  name:              Heather Arthur
  url:               https://twitter.com/heathermakes
  email:             heather@webscale.co.uk

# Custom vars
version:             1.0.0

plugins: [jekyll-paginate]
